In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [22]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [23]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [24]:
## Define the vocabulary size
voc_size=10000

In [25]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [26]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1779, 384, 9989, 4307],
 [1779, 384, 9989, 6553],
 [1779, 9798, 9989, 342],
 [771, 1364, 1680, 8480, 8259],
 [771, 1364, 1680, 8480, 781],
 [7050, 1779, 521, 9989, 1179],
 [7026, 4384, 6826, 8480]]

In [27]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [28]:
import numpy as np

In [29]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1779  384 9989 4307]
 [   0    0    0    0 1779  384 9989 6553]
 [   0    0    0    0 1779 9798 9989  342]
 [   0    0    0  771 1364 1680 8480 8259]
 [   0    0    0  771 1364 1680 8480  781]
 [   0    0    0 7050 1779  521 9989 1179]
 [   0    0    0    0 7026 4384 6826 8480]]


In [30]:
## feature representation
dim=10

In [31]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')
model.build(input_shape=(None, sent_length))


In [32]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 254ms/step


array([[[ 1.42061748e-02, -1.45138130e-02,  2.73118280e-02,
          2.02215426e-02, -2.05212366e-02,  5.78414649e-04,
         -3.72975357e-02, -4.54578996e-02,  2.74007805e-02,
         -2.33614575e-02],
        [ 1.42061748e-02, -1.45138130e-02,  2.73118280e-02,
          2.02215426e-02, -2.05212366e-02,  5.78414649e-04,
         -3.72975357e-02, -4.54578996e-02,  2.74007805e-02,
         -2.33614575e-02],
        [ 1.42061748e-02, -1.45138130e-02,  2.73118280e-02,
          2.02215426e-02, -2.05212366e-02,  5.78414649e-04,
         -3.72975357e-02, -4.54578996e-02,  2.74007805e-02,
         -2.33614575e-02],
        [ 1.42061748e-02, -1.45138130e-02,  2.73118280e-02,
          2.02215426e-02, -2.05212366e-02,  5.78414649e-04,
         -3.72975357e-02, -4.54578996e-02,  2.74007805e-02,
         -2.33614575e-02],
        [ 3.13760974e-02,  3.56265940e-02,  1.09498575e-03,
          1.32749192e-02,  4.31714095e-02, -2.77641546e-02,
         -7.19226897e-04, -2.84469016e-02,  7.534958

In [34]:
embedded_docs[0]

array([   0,    0,    0,    0, 1779,  384, 9989, 4307], dtype=int32)

In [35]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None